### ISSUE TITLE
Set deafault page

### ISSUE THREAD

**Issue by YraelTheEighth** [notion-enhancer/repo#104]
**What makes the feature necessary?**
Notion by itself has the ability to set a default page (top page in sidebar). This works on exit and relaunch, but doesn't work on close and open from tray feature by dragonwocky. It would be helpful if this could be intergrated so that when the app is maximised from the tray, a selected page (or at least top page like base app) would always be the one to open.

**How would the feature work?**
Possibly a toggle in the options for the tray mod, or just using the option selected in Notion settings

**Comment by dragonwocky** [comment]
@YraelTheEighth the app doesn't "close" when it's minimised to the tray, it just gets hidden and then re-shown - it's designed so you can go back to where you were anytime quickly, without having to create a new window. If you want the default page to load, either click on it in the sidebar or fully quit and relaunch the app.
