### ISSUE TITLE
Use Notion Enhancer to insert/extract content from desktop Notion

### ISSUE THREAD

**Issue by pooriaarab** [notion-enhancer/repo#107]
Hi, 

I'm setting up a team to OSS or micro-SaaS notion to social media posting (Twitter, Instagram, LinkedIn...).

Instead of a chrome extension, wanted to set it up for notion desktop/mac as well. 

Curious for tips on using the API on interacting with the desktop Notion version and if this is even possible.

**Comment by dragonwocky** [comment]
Is this possible from within a notion-enhancer integration? Yes.

However, I would recommend building something with the official Notion API (https://developers.notion.com/) instead. The notion-enhancer is suitable for embedding buttons into the app that can perform a few API tasks, but for a more reliable/documented experience accessing Notion content it may be better to build an external tool.

You may also find these relevant:
- https://www.queue.so/
- https://zapier.com/apps/notion/integrations/twitter
