### ISSUE TITLE
Support Vim keybindings when editing a page

### ISSUE THREAD

**Issue by magnusrodseth** [notion-enhancer/repo#116]
**What makes the feature necessary?**

Supporting Vim keybindings is useful because many software engineers use Notion as their one-stop shop for note taking.

Additionally, there already exist alternatives to Notion that have implemented this, for instance [Inkdrop](https://my.inkdrop.app/plugins/vim). However, Inkdrop is a paid service, and lacks many of the major features Notion provides.

The suggested feature is enhancing because navigating a page is already possible, but not using Vim keybindings.

The suggested feature is also client-only.

Together, these points fulfill the criteria in the [Contributing docs](https://notion-enhancer.github.io/about/contributing/#feature).

Some example use cases include:

- I'm editing a page, and I want to navigate up, down, left or right. I want to use `h`, `j`, `k`, `l`, `b`, `w`, `f <char>`, `F <char>`, etc... to improve my productivity.
- I want to save my note. I want to use `:w` instead of `CMD + s`
- I want to alternate between two pages that I am editing. I want to use `CTRL + o` and `CTRL + i` instead of constantly searching for the two same pages.

**How would the feature work?**

See examples above for some scenarios on how to interact with the feature.

From a technical standpoint, Notion may provide some way to remap keybindings such as the `arrow keys`, `SHIFT + arrow keys`, etc...

**Comment by dragonwocky** [comment]
This feature has been requested a few times before, and my answer is still a definite no, for the reasons outlined here: https://github.com/notion-enhancer/desktop/issues/641

On your use-cases:

> I'm editing a page, and I want to navigate up, down, left or right. I want to use h, j, k, l, b, w, f <char>, F <char>, etc... to improve my productivity.

This is what arrow keys are for.

> I want to save my note. I want to use :w instead of CMD + s

Notion auto-saves. A keyboard shortcut to "save" the page is nothing but a visual reassurance. 

> I want to alternate between two pages that I am editing. I want to use CTRL + o and CTRL + i instead of constantly searching for the two same pages.

Try `ctrl+p` - it saves your most recently accessed pages, so to switch between 2 pages all you need to do is click `ctrl+p` and then hit `enter` on the first result.

On your suggested implementation:

> Additionally, there already exist alternatives to Notion that have implemented this, for instance [Inkdrop](https://my.inkdrop.app/plugins/vim). However, Inkdrop is a paid service, and lacks many of the major features Notion provides.

> From a technical standpoint, Notion may provide some way to remap keybindings such as the arrow keys, SHIFT + arrow keys, etc...

See the issue linked above - to my knowledge there is currently no way to remap keybindings, only add entirely new ones. Inkdrop's plugins are fundamentally different from notion-enhancer extensions, as Inkdrop provides configuration and deeply embedded customisation abilities (e.g. remapping built-in keybindings) to its plugins directly, while notion-enhancer extensions must apply over the top of Notion.

Sorry. If you can figure out how to implement Vim keybindings over Notion yourself, feel free to do so and make a pull request. I won't be working on this feature, though.
