### ISSUE TITLE
Multiple cursor feature 

### ISSUE THREAD

**Issue by DILPREET1910** [notion-enhancer/repo#121]
**What makes the feature necessary?**
you can create multiple cursors in order to add some text in multiple lines
instead of manually typing that same text in different lines, multiple times like a donkey.

**How would the feature work?**
If you are using microsoft's vscode you would probably already know this.
By holding ALT key and clicking you create multiple cursors.

it was a miss click **GO AWAY!**

**Comment by dragonwocky** [comment]
Unfortunately multi-cursor editing is probably beyond the scope of the notion-enhancer, it's a feature that could end up conflicting quite significantly with Notion's own handling of keyboard input and have unwanted side effects on your pages.

The kind of writing that works well in Notion, though, generally isn't repetitive in the same way code editing might be. I recommend sticking for VS Code when you need that kind of multi-cursor editing. If I do one day figure out how to do it, though, then sure, I'll keep it in mind to add to the notion-enhancer.
