### ISSUE TITLE
Weekly view enhanced

### ISSUE THREAD

**Issue by jgsource** [notion-enhancer/repo#13]
When I click on arrows, I would like for it to go to the following week instead of month so I can easily plan ahead. Is this bug or has it just not been implemented?

**Comment by ncoquelet** [comment]
Hello,
Since the official weekly calendar view support, the weekly mod is no longer necessary, right ?
https://twitter.com/NotionHQ/status/1628079143593349120

**Comment by dragonwocky** [comment]
Correct @ncoquelet, thanks for the pickup!
