### ISSUE TITLE
Changing the Color of the Title

### ISSUE THREAD

**Issue by kab521** [notion-enhancer/repo#131]
**What makes the feature necessary?**
Match the rest of the themes on notion, and makes it easier to distinguish that it is the title. 

**How would the feature work?**
Possibly the same way the user is able to change the colors of the text within pages.

**Comment by dragonwocky** [comment]
Are you asking for a CSS variable to change the colour of the title when making a theme, or for a way to change the colour per-title from within the Notion interface?

> Match the rest of the themes on notion

Which themes in particular are you referring to?

**Comment by kab521** [comment]
A way to change the colour of the title from the Notion interface.
