### ISSUE TITLE
Improve handling of images/screenshots

### ISSUE THREAD

**Issue by PatrickThonhauser** [notion-enhancer/repo#132]
Hello,

I recently started using Notion and so far I really love it.
However there is one thing that almost made me switch to other products -> image handling.

A use case I have seen many people have is to quickly insert images (from the clipboard) into tables and regular pages.
There are many use cases for this, adding images to documentation, bug reports, feature ideas in tables etc.

Issue with the current solution:

In Tables:

- you can't copy paste images into existing database tables, you can only upload images from your computer or link them from other sources
It would be great if this was possible, ideally allow to either only show a small preview and extend it to a larger view by clicking on it, or immediately showing it in full resolution

Image handling in general:

- It feels really wonky compared to other tools to deal with images right now.
- When pasting images onto the page they are automatically center-aligned, even if I switched the view of the page to full screen, which has all other contents automatically left-aligned
- When trying to resize images, the size does not follow my mouse cursor exactly but instead it has a short delay which makes it really tricky to actually resize them properly

I would love to see these things improved as many users that I have talked to have mentioned this :) 
Otherwise, great product so far!

**Comment by dragonwocky** [comment]
> When pasting images onto the page they are automatically center-aligned, even if I switched the view of the page to full screen, which has all other contents automatically left-aligned

You can change the default image alignment with the "image alignment" option of the tweaks extension in the notion-enhancer menu.

The other things are more complicated to fix and may not be possible with the notion-enhancer, but I'll have a think on that.
