### ISSUE TITLE
RTL User interface

### ISSUE THREAD

**Issue by webenadam** [notion-enhancer/repo#134]
Thanks for this great add-on to the notin-enhancer! It's a live saving.

Can you maybe try to add another add-on that will flip all the notion interface to RTL?

**Comment by dragonwocky** [comment]
@webenadam have you tried the right to left extension? It enables automatic RTL detection so that text in RTL languages (e.g. Arabic) will display as RTL.

I don't think it makes much sense to force the entire interface to RTL as it would cause issues with non-Arabic text, icons and interface layout.

**Comment by webenadam** [comment]
Yes I did. It’s very nice. But
My goal is to use it mainly RTL.

Icons can be flipped also with
transform: scaleX(-1); and so…


‫ב-6 ביוני 2023, בשעה 6:32, ‏‏⁨Tom⁩ ***@***.***⁩> כתב/ה:‬


@webenadam <https://github.com/webenadam> have you tried the right to left extension? It enables automatic RTL detection so that text in RTL languages (e.g. Arabic) will display as RTL.

I don't think it makes much sense to force the entire interface to RTL as it would cause issues with non-Arabic text, icons and interface layout.

**Comment by dragonwocky** [comment]
@webenadam I'm not sure that this is something I would be able to put time into, and I foresee more challenges than benefits of trying to use an English interface in RTL. If you would like to put together some CSS to do this via the custom css option under the tweaks mod, feel free! If you get it working, I'd be happy to merge it into the notion-enhancer.
