### ISSUE TITLE
Locking notes / databases feature

### ISSUE THREAD

**Issue by tamannarajpoot** [notion-enhancer/repo#136]
If notion had a function to lock notes or databases etc. with a pin code that would be incredible. An app that does this well is Day One and I use this for journaling every single day but I literally only use it because the app locks itself. 2FA/MFA is not the same because it compromises the ease of use but an added quick pin or password each time we open the app that we could toggle on or off would be amazing. 

**What makes the feature necessary?**
The feature is considered necessary because it provides an added layer of security for notes, databases, and other contents within the app. The user finds value in apps like Day One, which they use for journaling daily, primarily because of the lock functionality. Having the ability to lock with a pin ensures that the user's personal and sensitive content is protected, without compromising the ease of use.

**How would the feature work?**
The feature would work by allowing users to set a quick pin or password for the app. Each time the app is opened, users would be required to enter this pin or password to gain access. For added flexibility and user preference, there should be an option to toggle this feature on or off, ensuring that users who prioritize quick access over security can easily disable it.

**Comment by dragonwocky** [comment]
This is a feature that would have to be implemented by Notion, not the notion-enhancer. It has been requested before, and I gave it a go, but it ended up pretty seriously flawed, so I chose not to implement it. At best it was semi-useless as a security measure, at worst it led to a few of my pages getting corrupted/deleted.

The notion-enhancer runs after a page has loaded, which means any lock it could possibly set would be pseudo-security at best. You could bypass it simply by going into the devtools and viewing the page source to read what's there behind the lock screen anyway, or just... disabling the notion-enhancer. Sure, that might be enough security to stop your younger brother from getting in, but I would recommend locking your device or using some sort of guided access software when they're using the device if that's what your concerned about. It wouldn't be enough to stop anyone else seriously trying to get access to your notes.

Plus, the notion-enhancer isn't available on mobile and isn't tied to your Notion account at all, so again- if whoever you're concerned about got hold of your phone or tablet, or if they managed to get your sign-in details, the notion-enhancer wouldn't be able to do anything about it.

Sorry about that. You can try requesting this feature directly from Notion- but until it comes (if it ever does), I recommend better security practices around access to your accounts and devices in general, so locking individual pages isn't a concern. I would also like to point out that Notion is designed for productivity and note-taking, not storing highly sensitive information (i.e. passwords or bank details), which should be stored in a more specialised app like 1Password or Bitwarden etc. (You've asked for the feature to protect your journal, which is reasonable, but I wanted to give a comprehensive answer here for anyone else who also wants this feature and finds this issue.)

---

As a sidenote, what might be possible is an encrypted notes feature. You would have to view/edit your notes in a separate editor controlled by the notion-enhancer, which would then encrypt your notes and store the encrypted string within your currently open Notion page. Those notes could then only be accessed via the notion-enhancer's interface.

However, this would mean you would lose all support for formatting your notes, if that feature of the notion-enhancer ever ran into a bug or was broken by changes to Notion (or if the page they were on was edited/deleted) your notes could become corrupted, and you could never view those notes on your mobile device.

It would also be difficult sufficiently protect the encryption method/key to avoid it being easily reverse-engineerable. I think it would be possible, but encryption isn't an area I have a lot of experience in, and the notion-enhancer's source code is open for anyone to look over, so there would be a few challenges involved.

Between all those shortcomings, it's not a feature I'm super keen to build and not something that could be done in the near future anyway.
