### ISSUE TITLE
Notion Enhancer app not working for Mac OS

### ISSUE THREAD

**Issue by esmewang27** [notion-enhancer/repo#137]
**What is happening?**
Opening the NE app just causes the window to pop up and the gray circle spins forever. 
**What should be happening?**
Should open the NE app. It was working just two days ago.

**Screenshots (if applicable):**

**Operating system/browser name & version:**
Mac OS, browser not relevant, Sonoma 14.0 

**notion-enhancer and/or notion-repackaged version:**
Have uninstalled and tried using arm64 installer: [.dmg](https://github.com/notion-enhancer/notion-repackaged/releases/download/v2.0.18-1/Notion-Enhanced-2.0.18-1-arm64.dmg) and Portable arm64 build.

**notion-enhancer configuration (enabled/disabled mods and their settings):**
I've followed all the steps described above as well as the xattr step. When I load the Enhancer, it just opens the window and shows the spinning wheel for... forever. Just checking that there's nothing else I should be doing except using the browser or vanilla Notion. It just stopped working two days ago.

(I'm also a complete idiot with coding and know nothing, but I think I did follow the steps properly. I even installed Powershell and made myself an admin.)

I have also gone to the GitLab and tried to use the MacOS for patch-notion-enhanced, but that didnt' work either (I am a moron when it comes to coding but I've been able to fix the problem when installing the .dmg for Mac in the past, as well as the " and ) problems. This seems to be something I can't figure out no matter what.  

The fact that everyone in the Mac OS channel in the Discord is saying that they don't have a fix is what made me come here and report a bug.

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/notion-repackaged/issues/116 - it has worked for some on mac, hasn't worked for others.

**Comment by esmewang27** [comment]
Unfortunately, I seem to be one of the Mac users for whom it doesn't work, and I don't know enough about coding to risk using sudo on  anything. Will be patient for a future solution; thank you.

**Comment by keithgibson** [comment]
@esmewang27, I just got it working by taking the steps [here](https://github.com/notion-enhancer/notion-repackaged/issues/116#issuecomment-1801638782). It's pretty simple. The sudo-ing is limited and straight forward.

edit: would you look at that! Some of the code I needed to get it to work came from [one of your](https://github.com/notion-enhancer/notion-repackaged/issues/112#issuecomment-1791741156) past comments! Thank you. I hope the steps I laid out work for you. Feel free to DM me if you have questions about any of it.
