### ISSUE TITLE
Notion loading forever

### ISSUE THREAD

**Issue by matteo-dinoia** [notion-enhancer/repo#138]
**What is happening?**
After launching Notion-repackaged or notion-enhancer the application load the spinning icon and remain in that state forever.

**What should be happening?**
The app should load.

**Screenshots (if applicable):**
Just the loading screen.
https://pastebin.com/uCeYMFTs (for command line output)

**Operating system/browser name & version:**
Operating System: Arch Linux 6.5.9
KDE Plasma Version: 5.27

**notion-enhancer and/or notion-repackaged version:**
notion-enhancer and notion-repackaged  
versions: 2.0.18 and lower (try using the older release but does the same)

**notion-enhancer configuration (enabled/disabled mods and their settings):**
not applicable (just installed)

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/notion-repackaged/issues/116

**Comment by matteo-dinoia** [comment]
I tryed the solution in that bug-report but unfortunately neither the temporary nor the long term solution seem to do anything. It still just try to load forever.

**Comment by dragonwocky** [comment]
Hi @matteo-dinoia, sorry for the late response. If you need additional support you can post to the thread I linked describing what you've tried and what you're getting in more detail, or you can ask in one of the support channels over in Discord. I'm closing this issue as a duplicate, though.
