### ISSUE TITLE
[v0.11] Outliner plugin with Neutral theme got wrong font size in outliner panel

### ISSUE THREAD

**Issue by dev-techmoe** [notion-enhancer/repo#20]
**What is happening?**

When I enable Outliner plugin and Neutral theme at the same time, the font size in the outliner panel is broken.

**What should be happening?**

**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/7919562/147819162-6ba7053b-d19a-47c1-9543-c90949fda71d.png)

**Operating system/browser name & version:**

- Win 10
- Chrome  96.0.4664.110

**notion-enhancer and/or notion-repackaged version:**

- notion-enhancer browser extension ver 0.11.0.1

**notion-enhancer configuration (enabled/disabled mods and their settings):**

enabled plugins

- outliner

enabled theme

- Neutral

**Comment by dragonwocky** [comment]
closing in favour of notion-enhancer/notion-enhancer#881
