### ISSUE TITLE
Navigate to the previous or next entry of a database in the current view

### ISSUE THREAD

**Issue by s-kyy** [notion-enhancer/repo#23]
**problem**
I'd like to have the option to navigate to the next page of a database without having to go back to the database page and clicking to the next page. I'm not sure if this can be done with some development in this project or if only Notion themselves can add the feature, so I'm adding it here in case it could be possible. Please close automatically if this has been asked before / it's not relevant and link to existing conversations. Apologies in advance. 

**solution**
After opening a page from a database in Notion in the smaller "preview mode", have buttons to the left and right of the page that can navigate to the next entry of the database. The next page should be determined by the current database view + filters + sorting, so that the navigation buttons correspond with the order of pages you see on the current view. 

Alternatively, these buttons be closer together in one corner of the page. 

To be honest I'd love to have a swipe feature (especially on mobile), but that should something Notion should do probably.

**Comment by dragonwocky** [comment]
This is now part of Notion by default (in page preview mode):
![image](https://user-images.githubusercontent.com/16874139/150456342-16e4d3fa-84b1-4621-ac3c-2ccb2914b482.png)
