### ISSUE TITLE
[icon sets] search

### ISSUE THREAD

**Issue by fabiosangregorio** [notion-enhancer/repo#3]
With many icon packs it can be difficult to find the icon you're searching for. It would be awesome if we could search the icons based on some keywords, just like we can do with the default notion emojis. 
This would require associating the icons with some keywords. It could be done from the icon pack's json or through a specific filename pattern.

Here's an example provided:

![](https://i.imgur.com/KvxVpCE.png)

Let me know what you think.

**Comment by dragonwocky** [comment]
though this is the original issue, closing in favour of https://github.com/notion-enhancer/notion-enhancer/issues/882 which focuses more realistically/usefully on searching by set title instead of individual icons
