### ISSUE TITLE
Code line numbers are incorrect

### ISSUE THREAD

**Issue by yd-yin** [notion-enhancer/repo#38]
![image](https://user-images.githubusercontent.com/37136395/147868977-1075d9a1-2468-4903-a779-62a773f0dd51.png)

If I got it right, I think the 3&4, 5&6, 7&8 should be one line, and there should be a number at the line between 8 and 9, and a number after 10

**Comment by dragonwocky** [comment]
most likely caused by https://github.com/notion-enhancer/notion-enhancer/issues/897
