### ISSUE TITLE
Set a database template as default

### ISSUE THREAD

**Issue by iwconfig** [notion-enhancer/repo#46]
**What makes the feature necessary?**
When adding new items to a database where the template used is always or most often the same it is somewhat cumbersome to click multiple times to apply the template. Having the "New" button apply the set default template automatically would benefit a smoother workflow.

**How would the feature work?**
Preferably a toggle option, named "Make default" or something, inside this submenu
![bild](https://user-images.githubusercontent.com/10843441/148136647-6c07166b-792e-4e61-871c-8436fa5f189d.png)
Then just click "New" and presto!

**Comment by dragonwocky** [comment]
out of scope, the notion-enhancer can't override notion at that level

**Comment by iwconfig** [comment]
I see! That's too bad. :slightly_frowning_face:
