### ISSUE TITLE
Indentation Lines extension making the block options background opaque

### ISSUE THREAD

**Issue by blorbb** [notion-enhancer/repo#48]
**What is happening?**

When indentation lines are enabled, the `+` and 6 dots options to the left of a block becomes opaque, the same colour as the theme background. Most noticeable when on top of coloured backgrounds.

I could not figure out any CSS to fix it, adding a transparent background simply overlays it on top of the existing opaque colour.

**What should be happening?**

The background should be transparent.

**Screenshots (if applicable):**

With indentation lines on:
![image](https://user-images.githubusercontent.com/88137137/148478232-0110bdce-5195-4623-9006-a94378d2784d.png)

With indentation lines off/unenhanced notion:
![image](https://user-images.githubusercontent.com/88137137/148478439-4972cd07-8a0d-431f-bac9-e3e95d49f45b.png)

**Operating system/browser name & version:**

Windows 10 21H1

**notion-enhancer and/or notion-repackaged version:**

notion repackaged v0.11.0

**notion-enhancer configuration (enabled/disabled mods and their settings):**

indentation lines - all modes

**Comment by dragonwocky** [comment]
this is intentional, otherwise the dots and lines overlap and can't be distinguished clearly.
