### ISSUE TITLE
rtl does not work

### ISSUE THREAD

**Issue by aliafshany** [notion-enhancer/repo#49]
Hello there, I'm running Opera Version 82.0.4227.43 (x86 64) on a Mac.

Regrettably, the RTL and theme installation will fail.

I've cleared the cache and restarted opera, but nothing has changed.

What would you suggest I do to resolve this?

best

https://user-images.githubusercontent.com/40741745/148651665-36a3d95d-f7ab-4c92-a7a2-3e84cf4a7a93.mov

.

**Comment by aliafshany** [comment]
![image](https://user-images.githubusercontent.com/40741745/148672095-f33488d0-19bc-4e76-98ad-55c0410a79eb.png)
![image](https://user-images.githubusercontent.com/40741745/148672100-b44c5089-6b5f-4b56-aad0-6233b47f88c1.png)
![image](https://user-images.githubusercontent.com/40741745/148672109-ec6674c0-0ff4-47bc-9784-b3398f46cc91.png)
![image](https://user-images.githubusercontent.com/40741745/148672193-a16b94fd-0711-432f-bc2d-ce5708ce1da6.png)

**Comment by dragonwocky** [comment]
related to https://github.com/obahareth/notion-rtl/issues/28, a fix is yet to be found

**Comment by dragonwocky** [comment]
The right to left extension should be fixed now - Notion has made an exception in the security feature that was blocking it (https://github.com/obahareth/notion-rtl/issues/28#issuecomment-1017756589). You may need to refresh your cache to load the latest version of Notion.
