### ISSUE TITLE
Panel site history

### ISSUE THREAD

**Issue by foxdoescode** [notion-enhancer/repo#5]
**problem**
I embed google using panel sites to do research while taking notes and it would be useful to go back to the previous page.

**solution**
how will this feature appear/act?
![image](https://user-images.githubusercontent.com/75043185/101899161-5780b100-3b7b-11eb-8f15-4d0386e44564.png)

This would require extending the panel options to either include back and forward as even more special cases or make a general icon api that would allow each mod to implement its own icons.

For storing the history, it would just require an onload listener, a list of urls, and an index.

**alternatives**
one could use a browser and constantly switch between the browser and notion but that context switching is unnecessary.

**Comment by dragonwocky** [comment]
closing since the panel-sites extension no longer exists
