### ISSUE TITLE
Customisable shortcuts

### ISSUE THREAD

**Issue by wuziqi-cmu** [notion-enhancer/repo#56]
**What makes the feature necessary?**
Not sure is it possible or not (not sure if this is enhancing or adding according to what says in the contributing guide), but adding such a feature would largely improve productivity. For example, now deleting a page on the sidebar does not have a shortcut. It would be great if the user can assign shortcuts to items available in the right-click menu.

**How would the feature work?**
Just like all other apps out there, have a separate settings section for shortcuts.

**Comment by dragonwocky** [comment]
no.

for features available through the notion-enhancer (e.g. toggling the extra sidebar or tabs), related hotkeys have been made customisable through the menu.

general hotkey customisation of builtin parts of notion is out of scope:
- every action would need to be programmed manually to be available, there are no available hooks
- there's no way to disable notion's existing hotkeys
