### ISSUE TITLE
Emoji picker / Can't type emojis – they flash for a second and disappear when I'm typing inside a doc

### ISSUE THREAD

**Issue by eileendai** [notion-enhancer/repo#57]
**What is happening?**
When typing an emoji after using the emoji picker (joypixels) in a page (so not using the emoji as an icon for the page), the emoji will flash for a second before disappearing.

**What should be happening?**
When typing the emoji, it should appear and not disappear.

**Screenshots (if applicable):**
Don't have screenshot but can provide screen recording.

**Operating system/browser name & version:**
Mac Monterey 12.1
Google chrome Version 97.0.4692.71 (Official Build) (arm64)

**notion-enhancer and/or notion-repackaged version:**
most recent as of today

https://user-images.githubusercontent.com/14115705/149712032-835cdcc4-2102-499d-85e7-c9e2109a4b1f.mov

**notion-enhancer configuration (enabled/disabled mods and their settings):**
The only thing I switched on is emoji picker (set to joypixels)

**Comment by a-marionette** [comment]
Bump, same issue

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-enhancer/issues/747
