### ISSUE TITLE
Themes are not properly showing themeing the header

### ISSUE THREAD

**Issue by pujiii** [notion-enhancer/repo#58]
**What is happening?**
The headers of pages are showing up with the colour of the default notion theme, instead of the given 

**What should be happening?**
They should be the colour given by the theme

**Screenshots (if applicable):**
![Notion_Enhanced](https://user-images.githubusercontent.com/33569475/150319277-ef11d258-08d5-4bef-90d9-983d0e3b0dc4.png)
![Notion_Enhanced](https://user-images.githubusercontent.com/33569475/150319283-f2304a12-a083-4779-8200-aeac1e0a1175.png)

Operating system/browser name & version:
Windows 11

notion-enhancer and/or notion-repackaged version:
notion-enhancer v0.11.0-dev

notion-enhancer configuration (enabled/disabled mods and their settings):
extensions: integrated titlebar, scroll to top, indentation lines, emoji sets, topbar icons, code line numbers, collapsible headers, focus mode

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-enhancer/issues/892
