### ISSUE TITLE
Themes and plugins are not affecting icon and title page section

### ISSUE THREAD

**Issue by ilyamikcoder** [notion-enhancer/repo#61]
**What is happening?**
All themes are not affecting this top section of pages. Icon sets extension is not working too, so I guess this section is not selectable by notion-enchancer whatsoever.

**What should be happening?**
Themes and plugins should be able to reach top section of the page.

**Screenshots (if applicable):**
![изображение](https://user-images.githubusercontent.com/37904672/150622619-699435b2-8795-4e3b-ba0a-22b06fa123ec.png)

**Operating system/browser name & version:**
Windows 11 / Firefox 96.0.1

**notion-enhancer and/or notion-repackaged version:**
notion-enhancer v0.11.0.1

**notion-enhancer configuration (enabled/disabled mods and their settings):**
```
outliner
scroll to top (1000px and 10%)
indentation lines (all toggles on, solid style)
word counter
code line numbers (don't number singlelined blocks, plain style)
truncated titles (all toggles on)
dark+ (rgba(31, 220, 15, 1) and rgba(235, 32, 231, 1))
```

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/notion-enhancer/issues/892
