### ISSUE TITLE
Pressing Download Profile Button Causes Notion Enhancer to crash and reopen

### ISSUE THREAD

**Issue by matturenovich** [notion-enhancer/repo#71]
**What is happening?**
When I click on the Save Button in the Profile section of Notion Enhancer on Mac Desktop it crashes the app and reopens it. I can click the manual download button to save the profile but the Save button causes the crash every time.

**What should be happening?**
A finder prompt should open allowing me to select where I want the save file to download to.

**Screenshots (if applicable):**
[https://cln.sh/iwpeWx](https://cln.sh/iwpeWx) - Screen Capture Video of Issue

**Operating system/browser name & version:**
Mac OS 11.6.2 Big Sur

**notion-enhancer and/or notion-repackaged version:**
Notion-Enhancer Version 2.0.18-1 (2.0.18-1) - App Info
notion-enhancer v0.11.0-dev - Notion Enhancer Info

**notion-enhancer configuration (enabled/disabled mods and their settings):**
[https://pastebin.com/9HjqbzTb](https://pastebin.com/9HjqbzTb)

**Comment by dragonwocky** [comment]
I think you've misunderstood the buttons. From left to right, they do the following:
- Downloads the profile as a `.json` file.
- Opens a file picker to upload a `.json` file.
- Saves changes to the profile (e.g. selecting a new profile or renaming a profile) and restarts the app to apply those changes.
- Deletes the active profile and restarts the app to load the next profile in the list.

**Comment by matturenovich** [comment]
Wow I don't know why I didnt realize that at all. 🤦🏼‍♂️  Sorry about that!
