### ISSUE TITLE
Ability to choose different languages

### ISSUE THREAD

**Issue by theisjendal** [notion-enhancer/repo#76]
**What makes the feature necessary?**
Currently, Notion supports English (US), Korean, and Japanese. This is a very short list. If you are not taking notes in English or write in American English, you are bound to have red lines all over your notes. 

**How would the feature work?**
The feature should allow the user to select more languages. Not necessarily for the menus but at least for the spelling.

**Comment by dragonwocky** [comment]
I've always planned to do this eventually, but not in the foreseeable near future.

**Comment by theisjendal** [comment]
That is understandable. If lucky, notion themselves will do it instead :-)

**Comment by renan-batista** [comment]
I'm in Brazil and I have the same problem, I always keep the spell checker disabled to not have only red lines. It would be very fair to be able to choose the correction language, as this harms all the content that is inside the application.
