### ISSUE TITLE
Outliner mod causes slow page scrolling

### ISSUE THREAD

**Issue by Edemilorhea** [notion-enhancer/repo#77]
BEFORE MAKING A BUG REPORT, PLEASE READ THE
[CONTRIBUTING](https://notion-enhancer.github.io/about/contributing) GUIDE.

BUG REPORTS ARE NOT FOR SUPPORT REQUESTS. IF YOU JUST NEED HELP,
ASK IN THE [DISCORD](https://discord.gg/sFWPXtA) SERVER.

BUG REPORTS THAT DO NOT PROPERLY FILL
IN THE TEMPLATE MAY BE IGNORED OR REJECTED.
YOU MUST DELETE ALL TEXT ON OR ABOVE THIS LINE BEFORE SUBMITTING.

**What is happening?**

The mod outliner causes slow page scrolling

**What should be happening?**

Make the page scroll normally

**Screenshots (if applicable):**

**Operating system/browser name & version:**

OS: Windows 11 21H2 

**notion-enhancer and/or notion-repackaged version:**

2.0.18-1 2.0.18-1

**notion-enhancer configuration (enabled/disabled mods and their settings):**

enabled outliner mod

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/repo/issues/77
