### ISSUE TITLE
Math Shortcut

### ISSUE THREAD

**Issue by dnswd** [notion-enhancer/repo#81]
**What makes the feature necessary?**
Math typing on Notion can be tedious depending on how dense maths in your note is. Every time you need to type in latex, you have to type `/math` and choose either `inline math` or `block equation`. This might sounds minor, but this slash command can disturb your train of thought really quick, especially if your notes full of equations. It would be better if there's shorter and separate shortcut for inline math and math block. I think this feature would help STEM students a lot.

By the time I write this issue, [notion doesn't have any math shortcut](https://www.notion.so/help/keyboard-shortcuts) except the `/math` "shortcut" I described above. 

**How would the feature work?**
Any shorter shortcut will do, I would prefer `$+enter` for inline math, and `$$+enter` to add an equation block below current block.

I would be happier if there's a way to make an inline math [like Typora did](https://i.imgur.com/6T4JywE.gif). Though, I know it would be difficult, so the former solution would be more than enough for me.

**Comment by albertopasqualetto** [comment]
@dnswd For the inline math you can do CTRL+MAIUSC+E; it is a Notion default shortcut, but your idea is still good.

**Comment by dragonwocky** [comment]
Notion does have a shortcut for this! If you type `$$`, then fill in your equation, then close it off with `$$`, it will wrap everything between the dollar signs into an inline math block.

For block-level math, you can type `/eq` and then hit enter. It should automatically select and create a block equation for you. No need to type the full `/math` and no need to manually select from the two options.
