### ISSUE TITLE
Lags (again)

### ISSUE THREAD

**Issue by TvoozMagnificent** [notion-enhancer/repo#83]
OK. Please do not close this because I get what you are saying. 
Closing word_counter did half the job. 
The other half can't be done. 
I did all of your suggestions, none work. 
Currently, it is half-lag:
I can control it but response speed is still super slow. 
(for the word counter maybe try manual refresh, not auto) 
Closing themes didn't work. 
Still, I kept it closed just in case. 
Any other possibilities? 
Add on conflicts? 
Mac causing problems? 
My disc space? 
<img width="137" alt="Screen Shot 2022-02-22 at 7 12 34 PM" src="https://user-images.githubusercontent.com/98521363/155121126-03b52f72-1e26-49af-adb2-3bace10e31d4.png">

**Comment by TvoozMagnificent** [comment]
Whoops sorry pressed something wrong.

**Comment by dragonwocky** [comment]
Please update this to match the provided issue template.

**Comment by TvoozMagnificent** [comment]
Um what is the issue template
thanks

**Comment by dragonwocky** [comment]
Click "New Issue" -> "Bug Report", the text box will have some stuff pre-filled.

Read and then delete the CAPITALISED text at the top.

Keep the \*\*bolded\*\* questions/headings and fill in the information beneath.

**Comment by TvoozMagnificent** [comment]
OK
