### ISSUE TITLE
LAGGING

### ISSUE THREAD

**Issue by TvoozMagnificent** [notion-enhancer/repo#84]
OK. Please do not close this because I get what you are saying. 
Closing word_counter did half the job. 
The other half can't be done. 
I did all of your suggestions, none work. 
Currently, it is half-lag:
I can control it but response speed is still super slow. 
(for the word counter maybe try manual refresh, not auto) 
Closing themes didn't work. 
Still, I kept it closed just in case. 
Any other possibilities? 
Add on conflicts? 
Mac causing problems? 
My disc space? 
<img width="137" alt="Screen Shot 2022-02-22 at 7 12 34 PM" src="https://user-images.githubusercontent.com/98521363/155121126-03b52f72-1e26-49af-adb2-3bace10e31d4.png">

**What is happening?**
Lagging

**What should be happening?**
Shouldn't lag

**Operating system/browser name & version:**
App version, <img width="226" alt="Screen Shot 2022-02-22 at 7 31 31 PM" src="https://user-images.githubusercontent.com/98521363/155123762-964a2096-f936-46c5-95b5-3c75aea6eb16.png">

**notion-enhancer and/or notion-repackaged version:**
Newest (0.11.0)

**notion-enhancer configuration (enabled/disabled mods and their settings):**
I have `fontchooser`, `tray, tabs`, `view scale`, `scroll to top`, `indentation lines`, `bypass preview`, and `truncated titles` on.

**Comment by TvoozMagnificent** [comment]
# Anyone?

**Comment by dragonwocky** [comment]
yeah, nothing I can do about this without real or specific diagnosis of the problem (e.g. #87)

¯\_(ツ)_/¯

github issues are for reporting specific bugs, not for asking for support with a personal usage issue. reopening/creating similar issues will result in them being closed, because "lag" is not a fixable bug when it doesn't have a known source.

**Comment by ReiTheMartian** [comment]
I had the same problem. I disabled each extension one by one until it stopped lagging, I assume you have already tried this but just in case, I recommend doing it, it might be an unexpected extension. For me it ended up being a combination of outliner and word counter. Very unexpected.

Major lag spikes would happen as outliner loaded in and it continued to stutter even after the page was loaded. Disabling one fixed half the lag, disabling the other fixed the other half. It now works as expected. I am on a very different much more beefy system though so your mileage may vary.

**Comment by TvoozMagnificent** [comment]
I tried with every file and only big files caused problems. 
FIX: smaller files.
