### ISSUE TITLE
Collapsible headers causes CPU usage to spike (A/B Tested: 15% baseline vs. 120%)

### ISSUE THREAD

**Issue by mich-dooley** [notion-enhancer/repo#87]
**What is happening?**
When Collapsible Headers extension is enabled, CPU usage spikes to 100%+. When disabled, the baseline is about 15%.
**What should be happening?**
The CPU usage should be... more reasonable.
**Screenshots (if applicable):**
When enabled:
<img width="940" alt="image" src="https://user-images.githubusercontent.com/62319117/155820489-06c2c45a-8e53-408e-9205-747395732f2e.png">

**Operating system/browser name & version:**
MacOS 12.2.1
**notion-enhancer and/or notion-repackaged version:**
notion-enhancer v0.11.0-dev (Notion Enhanced dmg downloaded today).
**notion-enhancer configuration (enabled/disabled mods and their settings):**
outliner, truncated titles, collapsible properties enabled

**Comment by dragonwocky** [comment]
Yeah... there are a couple of mods that aren't particularly efficient on larger pages, unfortunately. I improve them a bit with each update but there's only so much that can be done.

This mod is obsolete and soon to be removed anyway, though - try Notion's new builtin toggle header blocks.
<img width="417" alt="image" src="https://user-images.githubusercontent.com/16874139/152702848-d50e0ce1-91f4-449a-a674-277fcd9e2556.png">

**Comment by chrisdlees** [comment]
@dragonwocky I think the collapsable headers mod would be nice, even with the Notion (R) Official {TM} collapsible blocks, as I move a lot of notes from Obsidian into Notion; this saved having to go in and change all the H's in my notes into a different special H after the Obsidian --> Notion MD import.  :p

**Comment by efemkay** [comment]
Yeah. I agree with @chrisdlees, as I also have quite a number of writeups that I don't think want to change to toggle header / collapsible block. coz i want to move to other documents as well. hope dev can consider continue support the mod
