### ISSUE TITLE
Outliner tray content overflow

### ISSUE THREAD

**Issue by stark-3k** [notion-enhancer/repo#90]
If I have a long document with many headings and subheadings, the content is overflowing from the Outliner tray. 

Ideally the content should be contained within the tray and I should be able to scroll through it.

![notion](https://user-images.githubusercontent.com/62797354/156229998-1a859303-9ca0-49d5-822e-15165f5a248b.gif)

Produced in macOS Big Sur
notion-enhancer version 0.11.0

**Comment by dragonwocky** [comment]
already reported in https://github.com/notion-enhancer/notion-enhancer/issues/881
