### ISSUE TITLE
Add the ability to generate title sequence numbers and globally modify code types

### ISSUE THREAD

**Issue by five-five0909** [notion-enhancer/repo#96]
Add the ability to generate title sequence numbers and globally modify code types

**Comment by dragonwocky** [comment]
I don't really understand what you mean here. Please update this with as much information as possible (see https://notion-enhancer.github.io/about/contributing/#feature for the minimum required).

**Comment by five-five0909** [comment]
![image](https://user-images.githubusercontent.com/66655057/158713646-3ff915cf-ac34-410e-9e3d-0e1cb2e019eb.png)
just like this photo

**Comment by dragonwocky** [comment]
I see. These are two distinct features, please open separate feature requests for them and fill in the provided issue template fully (answer and do not remove the headings in `**bold**`).
